export const dataList =[
    {
        "register_seq": 37005,
        "person_id": 3521300211768,
        "person_firstnameth": "นางสกุลรัตน์",
        "person_middlenameth": null,
        "person_lastnameth": "หมุดดี",
        "person_fullname": "นางสกุลรัตน์ หมุดดี",
        "person_birthdate": "1978-08-01T00:00:00",
        "person_phone": "0931323673",
        "person_email": "pasin11@hotmail.com",
        "person_position": "นักวิชาการจัดเก็บรายได้ ชำนาญงาน",
        "province_seq": 40,
        "amphur_seq": 655,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 3842,
        "department_phone": "082132132",
        "user_id": "pasin11@hotmail.com",
        "user_password": "51f6ef152c374921c80a998c6399dfb4",
        "register_type_seq": 5,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T10:09:58",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T10:09:58",
        "landoffice_name": "องค์การบริหารส่วนตำบล ทุ่งกว๋าว",
        "province_name": "ลำปาง",
        "register_type_name": "จนท. (อปท.) - เเจ้งข้อผิดพลาด"
    },
    {
        "register_seq": 37007,
        "person_id": 3329900111135,
        "person_firstnameth": "นางสาวณัฐทิรา",
        "person_middlenameth": null,
        "person_lastnameth": "ทัดศรี",
        "person_fullname": "นางสาวณัฐทิรา ทัดศรี",
        "person_birthdate": "1980-11-16T00:00:00",
        "person_phone": "0822056993",
        "person_email": "6320513@dla.go.th",
        "person_position": "เจ้าพนักงานจัดเก็บรายได้",
        "province_seq": 21,
        "amphur_seq": 298,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 6861,
        "department_phone": "044069726",
        "user_id": "6320513@dla.go.th",
        "user_password": "53988eaae0f068ccd2aa040129792fbd",
        "register_type_seq": 4,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T10:14:46",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T10:14:46",
        "landoffice_name": "องค์การบริหารส่วนตำบล ทุ่งมน",
        "province_name": "สุรินทร์",
        "register_type_name": "จนท. (อปท.) - รับข้อมูลมาตรา 10"
    },
    {
        "register_seq": 37008,
        "person_id": 3311000426612,
        "person_firstnameth": "ลลดา",
        "person_middlenameth": null,
        "person_lastnameth": "อินช้าง",
        "person_fullname": "ลลดา อินช้าง",
        "person_birthdate": "1983-03-27T00:00:00",
        "person_phone": "0981978351",
        "person_email": "saraban_06310416@dla.go.th",
        "person_position": "นักวิชาการจัดเก็บรายได้ชำนาญการ",
        "province_seq": 20,
        "amphur_seq": 273,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 446,
        "department_phone": "044110720",
        "user_id": "saraban_06310416@dla.go.th",
        "user_password": "fbdc64a0abf4cb9ad8b5f8b9d31e5908",
        "register_type_seq": 4,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T10:24:17",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T10:24:17",
        "landoffice_name": "องค์การบริหารส่วนตำบล หัวถนน",
        "province_name": "บุรีรัมย์",
        "register_type_name": "จนท. (อปท.) - รับข้อมูลมาตรา 10"
    },
    {
        "register_seq": 37011,
        "person_id": 3329900111135,
        "person_firstnameth": "นางสาวณัฐทิรา  ",
        "person_middlenameth": null,
        "person_lastnameth": "ทัดศรี",
        "person_fullname": "นางสาวณัฐทิรา   ทัดศรี",
        "person_birthdate": "1980-11-16T00:00:00",
        "person_phone": "0822056993",
        "person_email": "nattira2555@gmail.com",
        "person_position": "เจ้าพนักงาจัดเก็บรายได้",
        "province_seq": 21,
        "amphur_seq": 298,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 6861,
        "department_phone": "044069726",
        "user_id": "nattira2555@gmail.com",
        "user_password": "53988eaae0f068ccd2aa040129792fbd",
        "register_type_seq": 5,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T10:30:10",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T10:30:10",
        "landoffice_name": "องค์การบริหารส่วนตำบล ทุ่งมน",
        "province_name": "สุรินทร์",
        "register_type_name": "จนท. (อปท.) - เเจ้งข้อผิดพลาด"
    },
    {
        "register_seq": 37013,
        "person_id": 3311000426612,
        "person_firstnameth": "ลลดา",
        "person_middlenameth": null,
        "person_lastnameth": "อินช้าง",
        "person_fullname": "ลลดา อินช้าง",
        "person_birthdate": "2526-03-27T00:00:00",
        "person_phone": "0981978351",
        "person_email": "glay.lalada@gmail.com",
        "person_position": "นักวิชาการจัดเก็บรายได้ชำนาญการ",
        "province_seq": 20,
        "amphur_seq": 273,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 446,
        "department_phone": "044110720",
        "user_id": "glay.lalada@gmail.com",
        "user_password": "fbdc64a0abf4cb9ad8b5f8b9d31e5908",
        "register_type_seq": 5,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T10:39:28",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T10:39:28",
        "landoffice_name": "องค์การบริหารส่วนตำบล หัวถนน",
        "province_name": "บุรีรัมย์",
        "register_type_name": "จนท. (อปท.) - เเจ้งข้อผิดพลาด"
    },
    {
        "register_seq": 37014,
        "person_id": 3610100256634,
        "person_firstnameth": "นางสาวจิตติมา",
        "person_middlenameth": null,
        "person_lastnameth": "ถุนนอก",
        "person_fullname": "นางสาวจิตติมา ถุนนอก",
        "person_birthdate": "1981-05-19T00:00:00",
        "person_phone": "0884947529",
        "person_email": "saraban_06610107@dla.go.th",
        "person_position": "นักวิชาการจัดเก็บรายได้ปฏิบัตการ",
        "province_seq": 48,
        "amphur_seq": 750,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 6712,
        "department_phone": "056503145",
        "user_id": "saraban_06610107@dla.go.th",
        "user_password": "46652a1b2e2020f2aebed40c8fb71d36",
        "register_type_seq": 4,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T10:48:46",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T10:48:46",
        "landoffice_name": "องค์การบริหารส่วนตำบล ดอนขวาง",
        "province_name": "อุทัยธานี",
        "register_type_name": "จนท. (อปท.) - รับข้อมูลมาตรา 10"
    },
    {
        "register_seq": 37015,
        "person_id": 3440900252643,
        "person_firstnameth": "มานิต",
        "person_middlenameth": null,
        "person_lastnameth": "ปิโคทัง",
        "person_fullname": "มานิต ปิโคทัง",
        "person_birthdate": "1971-09-10T00:00:00",
        "person_phone": "0942729661",
        "person_email": "saraban_06440910@dla.go.th",
        "person_position": "ผู้ช่วยเจ้าหน้าที่จัดเก็บรายได้",
        "province_seq": 32,
        "amphur_seq": 517,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 4093,
        "department_phone": "043750735",
        "user_id": "saraban_06440910@dla.go.th",
        "user_password": "1f1c23401e5893c462e10485d2a571a2",
        "register_type_seq": 4,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T10:51:28",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T10:51:28",
        "landoffice_name": "องค์การบริหารส่วนตำบล ขามป้อม",
        "province_name": "มหาสารคาม",
        "register_type_name": "จนท. (อปท.) - รับข้อมูลมาตรา 10"
    },
    {
        "register_seq": 37016,
        "person_id": 1341900141936,
        "person_firstnameth": "วัชรีวรรณ ",
        "person_middlenameth": null,
        "person_lastnameth": "ฝางคำ",
        "person_fullname": "วัชรีวรรณ  ฝางคำ",
        "person_birthdate": "1990-01-15T00:00:00",
        "person_phone": "0968146261",
        "person_email": "6342502@dla.go.th",
        "person_position": "นักวิชาการจัดเก็บรายได้ปฏิบัติการ",
        "province_seq": 23,
        "amphur_seq": 353,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 736,
        "department_phone": "045251967",
        "user_id": "6342502@dla.go.th",
        "user_password": "eee2bc489376a39dc21ae8c12470b17e",
        "register_type_seq": 4,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T10:56:58",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T10:56:58",
        "landoffice_name": "องค์การบริหารส่วนตำบล คันไร่",
        "province_name": "อุบลราชธานี",
        "register_type_name": "จนท. (อปท.) - รับข้อมูลมาตรา 10"
    },
    {
        "register_seq": 37019,
        "person_id": 3820200016421,
        "person_firstnameth": "กุลธิดา",
        "person_middlenameth": null,
        "person_lastnameth": "ภู่สอาด",
        "person_fullname": "กุลธิดา ภู่สอาด",
        "person_birthdate": "1971-11-28T00:00:00",
        "person_phone": "0869482973",
        "person_email": "m_kultida_p@hotmail.com",
        "person_position": "เจ้าหนักงานการเงินและบัญชีชำนาญงาน",
        "province_seq": 65,
        "amphur_seq": 938,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 5296,
        "department_phone": "076597122",
        "user_id": "m_kultida_p@hotmail.com",
        "user_password": "c1abf707920e629de3d99d98e6de5eb7",
        "register_type_seq": 5,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T11:54:20",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T11:54:20",
        "landoffice_name": "องค์การบริหารส่วนตำบล เกาะยาวน้อย",
        "province_name": "พังงา",
        "register_type_name": "จนท. (อปท.) - เเจ้งข้อผิดพลาด"
    },
    {
        "register_seq": 37020,
        "person_id": 3570700156666,
        "person_firstnameth": "สายรู้ง",
        "person_middlenameth": null,
        "person_lastnameth": "สุวรรณ์",
        "person_fullname": "สายรู้ง สุวรรณ์",
        "person_birthdate": "1975-07-26T00:00:00",
        "person_phone": "0864300255",
        "person_email": "saraban_05570902@dla.go.th",
        "person_position": "ผู้อำนวยการกองคลัง",
        "province_seq": 45,
        "amphur_seq": 711,
        "landoffice_id": null,
        "department_seq": null,
        "department_name": null,
        "opt_seq": 2951,
        "department_phone": "053763235",
        "user_id": "saraban_05570902@dla.go.th",
        "user_password": "4433345fb41cea0ad82f807e74e7ffe9",
        "register_type_seq": 4,
        "approve_flag": null,
        "register_ad_flag": null,
        "register_openid_token": null,
        "register_objective": " ",
        "remark": " ",
        "record_status": "N",
        "create_user": "1",
        "create_dtm": "2025-01-20T13:07:25",
        "last_upd_user": "1",
        "last_upd_dtm": "2025-01-20T13:07:25",
        "landoffice_name": "เทศบาลตำบล ห้วยไคร้",
        "province_name": "เชียงราย",
        "register_type_name": "จนท. (อปท.) - รับข้อมูลมาตรา 10"
    }
]
